import { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, GraduationCap, PlusCircle } from 'lucide-react';
import api, { getErrorMessage } from '../api';
import './LearningJourney.css';

const labelLevel = v => v === 'ADVANCED' ? 'Proficient' : v === 'INTERMEDIATE' ? 'Intermediate' : 'Beginner';

export default function LearningJourney(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(null);
 const load=()=>api.get('/learning').then(r=>setItems(r.data.progress||[])).catch(e=>setError(getErrorMessage(e,'Could not load your learning journey.'))).finally(()=>setLoading(false));
 useEffect(()=>{load()},[]);
 const complete=async id=>{try{setBusy(id);await api.put(`/learning/${id}/complete`);await load()}catch(e){setError(getErrorMessage(e,'Could not confirm learning.'))}finally{setBusy(null)}};
 const add=async id=>{const level=window.prompt('Choose your level: BEGINNER, INTERMEDIATE or PROFICIENT','BEGINNER');if(!level)return;try{setBusy(id);await api.post(`/learning/${id}/add-to-profile`,{level:level.toUpperCase()});await load()}catch(e){setError(getErrorMessage(e,'Could not add this skill to your profile.'))}finally{setBusy(null)}};
 return <main className="learning-page"><div className="learning-shell"><header className="learning-header"><div><span className="eyebrow">YOUR LEARNING JOURNEY</span><h1>Turn every exchange into a <span>real skill.</span></h1><p>You learn from another student, complete the exchange, confirm what you learned, then add the skill to your profile.</p></div><div className="journey-map"><div className="done">1<span>Match</span></div><i/><div className="done">2<span>Session</span></div><i/><div>3<span>Confirm</span></div><i/><div>4<span>Profile</span></div></div></header>{error&&<div className="form-alert">{error}</div>}{loading?<div className="learning-empty">Loading your learning records…</div>:items.length===0?<div className="learning-empty"><GraduationCap size={44}/><h2>No learning journeys yet</h2><p>Find a match, exchange knowledge and your learning progress will appear here.</p></div>:<div className="learning-list">{items.map(item=><article className="learning-card" key={item.id}><div className="learning-icon"><GraduationCap/></div><div className="learning-main"><div className="learning-top"><div><span className="skill-label">YOU ARE LEARNING</span><h2>{item.skill_name}</h2><p>from <strong>{item.teacher_name}</strong>{item.teacher_department ? ` · ${item.teacher_department}`:''}</p></div><span className={`progress-pill ${item.status.toLowerCase()}`}>{item.status==='IN_PROGRESS'?<Clock3 size={14}/>:<CheckCircle2 size={14}/>} {item.status==='ADDED_TO_PROFILE'?'On profile':item.status==='COMPLETED'?'Completed':'In progress'}</span></div><div className="learning-meta"><span>Exchange session #{item.session_id}</span><span>Session: {item.session_status}</span></div><div className="learning-actions">{item.status==='IN_PROGRESS'&&<button onClick={()=>complete(item.id)} disabled={busy===item.id}> <CheckCircle2 size={16}/> {busy===item.id?'Saving…':'I completed learning this skill'}</button>}{item.status==='COMPLETED'&&<button onClick={()=>add(item.id)} disabled={busy===item.id}><PlusCircle size={16}/> {busy===item.id?'Adding…':'Add skill to my profile'}</button>}{item.status==='ADDED_TO_PROFILE'&&<span className="profile-added"><CheckCircle2 size={16}/> Skill added to profile</span>}</div></div></article>)}</div>}</div></main>;
}
