import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, MessageCircle, Send, Star, Video } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import api, { getErrorMessage } from '../api';
import './PeerProfile.css';

const initials = (name = 'Student') => name.split(/\s+/).filter(Boolean).map(x => x[0]).join('').slice(0,2).toUpperCase() || 'S';
const level = v => v === 'ADVANCED' ? 'PROFICIENT' : v || 'BEGINNER';
function Stars({ value }) { return <span className="peer-stars">{[1,2,3,4,5].map(n => <Star key={n} size={13} fill={value >= n ? 'currentColor' : 'none'}/>)}</span>; }

export default function PeerProfile() {
  const { id } = useParams(); const navigate = useNavigate();
  const [data,setData] = useState(null); const [ratings,setRatings] = useState({ summary:{}, ratings:[] }); const [offered,setOffered]=useState(''); const [requested,setRequested]=useState(''); const [message,setMessage]=useState(''); const [learningSessions,setLearningSessions]=useState(3); const [teachingSessions,setTeachingSessions]=useState(3); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{ Promise.all([api.get(`/matches/${id}`), api.get(`/users/${id}/ratings`)]).then(([m,r])=>{setData(m.data.match);setRatings(r.data)}).catch(e=>setError(getErrorMessage(e,'Could not load this student.'))); },[id]);
  const selectedLearn = useMemo(()=>data?.skillsTheyCanTeach?.find(s=>String(s.id)===String(requested)),[data,requested]); const selectedOffer = useMemo(()=>data?.skillsTheyWantToLearn?.find(s=>String(s.id)===String(offered)),[data,offered]);
  const send=async()=>{if(!offered||!requested)return setError('Choose one skill they can teach and one skill you can teach in return.');try{setBusy(true);setError('');await api.post('/requests',{receiver_id:Number(id),offered_skill_id:Number(offered),requested_skill_id:Number(requested),planned_learning_sessions:learningSessions,planned_teaching_sessions:teachingSessions,message:message.trim()||null});navigate('/requests');}catch(e){setError(getErrorMessage(e,'Could not send the exchange request.'));}finally{setBusy(false);}};
  if(error&&!data)return <main className="peer-page"><div className="peer-shell"><button className="peer-back" onClick={()=>navigate('/matches')}><ArrowLeft size={16}/> Back to matches</button><div className="peer-alert">{error}</div></div></main>;
  if(!data)return <main className="peer-page"><div className="peer-shell"><div className="peer-loading">Loading student profile…</div></div></main>;
  const average=Number(ratings.summary?.average_rating||0); const total=Number(ratings.summary?.total_ratings||0);
  return <main className="peer-page"><div className="peer-shell"><button className="peer-back" onClick={()=>navigate('/matches')}><ArrowLeft size={16}/> Back to matches</button>
    <section className="peer-hero"><div className="peer-avatar">{initials(data.user.name)}</div><div className="peer-main"><span>RECIPROCAL MATCH</span><h1>{data.user.name}</h1><p>{data.user.department || 'Student'}{data.user.college ? ` · ${data.user.college}` : ''}</p><div className="peer-rating">{average ? <><Stars value={average}/><strong>{average.toFixed(1)}</strong><small>{total} rating{total===1?'':'s'}</small></> : <small>New to ratings</small>}</div></div><div className="compatibility"><strong>{data.compatibilityScore}</strong><span>matching skills</span></div></section>
    {error&&<div className="peer-alert">{error}</div>}
    <div className="peer-grid"><section className="peer-panel teach-panel"><span>THEY CAN TEACH YOU</span><h2>Choose what you want to learn</h2><p>These are skills that overlap with your learning goals.</p><div className="peer-skill-list">{data.skillsTheyCanTeach.length?data.skillsTheyCanTeach.map(s=><button key={s.id} className={String(requested)===String(s.id)?'selected':''} onClick={()=>setRequested(s.id)}><div><strong>{s.name}</strong><small>{level(s.level)}</small></div>{String(requested)===String(s.id)?<Check/>:<ArrowRight/>}</button>):<div className="peer-empty">No matching teaching skill found.</div>}</div></section>
      <section className="peer-panel learn-panel"><span>YOU CAN GIVE BACK</span><h2>Choose what you will teach</h2><p>These are skills they want to learn from a partner.</p><div className="peer-skill-list">{data.skillsTheyWantToLearn.length?data.skillsTheyWantToLearn.map(s=><button key={s.id} className={String(offered)===String(s.id)?'selected':''} onClick={()=>setOffered(s.id)}><div><strong>{s.name}</strong><small>{level(s.level)}</small></div>{String(offered)===String(s.id)?<Check/>:<ArrowRight/>}</button>):<div className="peer-empty">No matching learning goal found.</div>}</div></section></div>
    <section className="peer-request"><div className="peer-request-heading"><div><span>EXCHANGE REQUEST</span><h2>Turn the match into a real learning plan.</h2></div><MessageCircle size={22}/></div><div className="peer-exchange-preview"><div><small>THEY TEACH YOU</small><strong>{selectedLearn?.name||'Choose a skill'}</strong></div><b>⇄</b><div><small>YOU TEACH THEM</small><strong>{selectedOffer?.name||'Choose a skill'}</strong></div></div><div className="peer-plan-grid"><label><span>Lessons you want to learn</span><select value={learningSessions} onChange={e=>setLearningSessions(Number(e.target.value))}>{[1,2,3,4,5,6,8,10].map(n=><option key={n} value={n}>{n} {n===1?'lesson':'lessons'}</option>)}</select></label><label><span>Lessons you will teach</span><select value={teachingSessions} onChange={e=>setTeachingSessions(Number(e.target.value))}>{[1,2,3,4,5,6,8,10].map(n=><option key={n} value={n}>{n} {n===1?'lesson':'lessons'}</option>)}</select></label></div><textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} placeholder="Write a short note about what you want to learn, what you can offer, or when you are available…"/><div className="peer-request-footer"><small>{message.length}/500 · The request will appear in their Requests page.</small><button onClick={send} disabled={busy||!offered||!requested}><Send size={15}/>{busy?'Sending…':'Send exchange request'}</button></div></section>
    <section className="peer-reviews"><div className="peer-section-title"><div><span>REPUTATION</span><h2>Feedback from previous exchanges</h2></div><strong>{average?average.toFixed(1):'—'}</strong></div>{ratings.ratings?.length?<div className="peer-review-grid">{ratings.ratings.slice(0,6).map(r=><article key={r.id}><div><div className="peer-review-avatar">{initials(r.reviewer_name)}</div><div><strong>{r.reviewer_name}</strong><small><Stars value={Number(r.rating)}/> {new Date(r.created_at).toLocaleDateString()}</small></div></div><p>{r.review||'No written feedback.'}</p></article>)}</div>:<div className="peer-empty large"><Star/><span>This student has no ratings yet. Completed sessions can create the first feedback.</span></div>}</section>
  </div></main>;
}
