import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import api, { getErrorMessage } from '../api';
import './PeerProfile.css';
export default function PeerProfile(){
 const {id}=useParams(); const nav=useNavigate(); const [data,setData]=useState(null),[offered,setOffered]=useState(''),[requested,setRequested]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api.get(`/matches/${id}`).then(r=>setData(r.data.match)).catch(e=>setError(getErrorMessage(e,'Could not load this student.')))},[id]);
 const send=async()=>{if(!offered||!requested)return setError('Choose the skill you will teach and the skill you want from this student.');try{setBusy(true);await api.post('/requests',{receiver_id:Number(id),offered_skill_id:Number(offered),requested_skill_id:Number(requested),message});nav('/requests')}catch(e){setError(getErrorMessage(e,'Could not send request.'))}finally{setBusy(false)}};
 if(!data&&!error)return <main className="peer-page"><div className="peer-card">Loading profile…</div></main>;
 if(error&&!data)return <main className="peer-page"><div className="peer-card"><div className="form-alert">{error}</div></div></main>;
 return <main className="peer-page"><div className="peer-shell"><button className="peer-back" onClick={()=>nav('/matches')}>← Back to matches</button><section className="peer-hero"><div className="peer-avatar">{data.user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><span className="eyebrow">SKILLSWAP STUDENT</span><h1>{data.user.name}</h1><p>{data.user.department||'Student'} · {data.user.college||'College'}</p><span>{data.user.bio||'Ready to exchange knowledge with another student.'}</span></div></section>{error&&<div className="form-alert">{error}</div>}<div className="peer-grid"><section className="peer-panel"><span className="section-kicker">THEY CAN TEACH YOU</span><h2>Choose one skill to learn</h2>{data.skillsTheyCanTeach.map(s=><button className={`peer-skill ${String(requested)===String(s.id)?'selected':''}`} key={s.id} onClick={()=>setRequested(s.id)}><span>{s.name}</span><b>{s.level==='ADVANCED'?'Proficient':s.level}</b></button>)}</section><section className="peer-panel"><span className="section-kicker">YOU CAN GIVE BACK</span><h2>Choose one skill to teach</h2><p className="panel-note">Your teaching skill is the knowledge you offer in return.</p>{data.skillsTheyWantToLearn.map(s=><button className={`peer-skill ${String(offered)===String(s.id)?'selected':''}`} key={s.id} onClick={()=>setOffered(s.id)}><span>{s.name}</span><b>{s.level==='ADVANCED'?'Proficient':s.level}</b></button>)}</section></div><section className="request-panel"><span className="section-kicker">EXCHANGE REQUEST</span><h2>Set up a two-way learning exchange</h2><div className="exchange-preview"><span>{data.user.name} teaches <strong>{data.skillsTheyCanTeach.find(s=>String(s.id)===String(requested))?.name||'—'}</strong></span><b>⇄</b><span>You teach <strong>{data.skillsTheyWantToLearn.find(s=>String(s.id)===String(offered))?.name||'—'}</strong></span></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Add a short message: what would you like to learn and when are you available?"/><button className="primary-submit" disabled={busy} onClick={send}>{busy?'Sending…':'Send exchange request →'}</button></section></div></main>;
}
