import { useState } from 'react';
import { Bell, Check, ChevronRight, KeyRound, Lock, LogOut, MessageCircle, Save, ShieldCheck, User, Video, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import api, { getErrorMessage } from '../api';
import { useAuth } from '../context/AuthContext';
import './Settings.css';

export default function Settings(){
  const navigate=useNavigate(); const {logout}=useAuth();
  const [notifications,setNotifications]=useState(()=>JSON.parse(localStorage.getItem('notifications') ?? 'true'));
  const [messageNotifications,setMessageNotifications]=useState(()=>JSON.parse(localStorage.getItem('messageNotifications') ?? 'true'));
  const [callNotifications,setCallNotifications]=useState(()=>JSON.parse(localStorage.getItem('callNotifications') ?? 'true'));
  const [security,setSecurity]=useState(false); const [currentPassword,setCurrentPassword]=useState(''); const [newPassword,setNewPassword]=useState(''); const [confirmPassword,setConfirmPassword]=useState('');
  const [notice,setNotice]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [passwordSaving,setPasswordSaving]=useState(false);
  const saveSettings=()=>{localStorage.setItem('notifications',JSON.stringify(notifications));localStorage.setItem('messageNotifications',JSON.stringify(messageNotifications));localStorage.setItem('callNotifications',JSON.stringify(callNotifications));setNotice('Preferences saved on this device.');setError('');};
  const updatePassword=async()=>{setError('');setNotice('');if(!currentPassword||!newPassword||!confirmPassword)return setError('Complete all password fields.');if(newPassword.length<8)return setError('New password must contain at least 8 characters.');if(newPassword!==confirmPassword)return setError('New passwords do not match.');try{setPasswordSaving(true);await api.put('/auth/password',{currentPassword,newPassword});setCurrentPassword('');setNewPassword('');setConfirmPassword('');setSecurity(false);setNotice('Password updated successfully.');}catch(e){setError(getErrorMessage(e,'Could not update your password.'));}finally{setPasswordSaving(false);}};
  const signOut=async()=>{setSaving(true);await logout();window.location.href='/';};
  const Toggle=({checked,onChange,disabled})=><label className={`switch ${disabled?'disabled':''}`}><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span className="slider"/></label>;
  return <main className="settings-page"><div className="settings-container"><button className="settings-back-button" onClick={()=>navigate('/dashboard')}>← Back to dashboard</button><div className="settings-header"><div><span className="settings-kicker">WORKSPACE PREFERENCES</span><h1>Settings</h1><p>Manage your account preferences and security.</p></div><button className="save-settings-button" onClick={saveSettings} disabled={saving}><Save size={17}/> Save changes</button></div>{notice&&<div className="settings-notice"><Check size={15}/>{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}{error&&<div className="settings-error">{error}<button onClick={()=>setError('')}><X size={14}/></button></div>}
    <section className="settings-section"><div className="section-title"><User size={19}/><div><h2>Account</h2><p>Your profile and authentication settings.</p></div></div><div className="settings-card"><button className="settings-item" onClick={()=>navigate('/profile')}><div className="settings-item-left"><div className="settings-icon"><User size={18}/></div><div><h3>Profile</h3><p>Update your name, bio and account information.</p></div></div><ChevronRight size={18}/></button><button className="settings-item" onClick={()=>setSecurity(true)}><div className="settings-item-left"><div className="settings-icon"><Lock size={18}/></div><div><h3>Password & security</h3><p>Change your password through the authenticated backend.</p></div></div><ChevronRight size={18}/></button></div></section>
    <section className="settings-section"><div className="section-title"><Bell size={19}/><div><h2>Notifications</h2><p>Choose which local workspace notifications you want to receive.</p></div></div><div className="settings-card"><div className="settings-item"><div className="settings-item-left"><div className="settings-icon"><Bell size={18}/></div><div><h3>Notifications</h3><p>Master switch for SkillSwap notifications.</p></div></div><Toggle checked={notifications} onChange={value=>{setNotifications(value);if(!value){setMessageNotifications(false);setCallNotifications(false)}}}/></div><div className={`settings-item ${!notifications?'disabled-setting':''}`}><div className="settings-item-left"><div className="settings-icon"><MessageCircle size={18}/></div><div><h3>Message notifications</h3><p>Notify me about new conversations.</p></div></div><Toggle checked={messageNotifications} disabled={!notifications} onChange={value=>{setMessageNotifications(value);if(value)setNotifications(true)}}/></div><div className={`settings-item ${!notifications?'disabled-setting':''}`}><div className="settings-item-left"><div className="settings-icon"><Video size={18}/></div><div><h3>Call notifications</h3><p>Notify me when an incoming call arrives.</p></div></div><Toggle checked={callNotifications} disabled={!notifications} onChange={value=>{setCallNotifications(value);if(value)setNotifications(true)}}/></div></div></section>
    <section className="settings-section danger-section"><div className="section-title danger-title"><LogOut size={19}/><div><h2>Account actions</h2><p>End your current authenticated session.</p></div></div><div className="settings-card"><button className="logout-button" onClick={signOut}><LogOut size={18}/> Sign out of SkillSwap</button></div></section>
  </div>{security&&<div className="security-overlay" onMouseDown={()=>setSecurity(false)}><div className="security-modal" onMouseDown={e=>e.stopPropagation()}><div className="security-modal-header"><div className="security-modal-title"><div className="security-modal-icon"><ShieldCheck size={22}/></div><div><h2>Password & security</h2><p>Update your password securely.</p></div></div><button className="security-close" onClick={()=>setSecurity(false)}><X size={18}/></button></div><div className="security-form"><label><span>Current password</span><div className="password-input"><KeyRound size={16}/><input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} autoComplete="current-password"/></div></label><label><span>New password</span><div className="password-input"><KeyRound size={16}/><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password"/></div></label><label><span>Confirm new password</span><div className="password-input"><KeyRound size={16}/><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password"/></div></label><div className="security-actions"><button className="security-cancel" onClick={()=>setSecurity(false)}>Cancel</button><button className="security-update" onClick={updatePassword} disabled={passwordSaving}>{passwordSaving?'Updating…':'Update password'}</button></div></div></div></div>}</main>;
}
